# Generated by Django 5.1.1 on 2024-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
